service:
  errors:
    notFoundChampionship: "Championship not found"
    unknown: "Unknown error"
    invalidArgument: "Invalid argument"
    alreadyExists: "Already exists"

model:
  errors:
    invalidArgument: "Invalid argument"
    
controller:
  errors:
    badRequest: "Bad request"