name: Run Frontend App

on:
  push:
    branches: 
     - 'development'
     - 'main' 
    paths:
      - 'frontend/**'
  pull_request:
    branches: 
     - 'development'
     - 'main' 
    paths:
      - 'frontend/**'

defaults:
 run:
  working-directory: ./frontend

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
     
      - uses: cypress-io/github-action@v5
      
      - name: Use Node.js ${{ matrix.node-version }}
         
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}


      - name: Install dependencies
        run: npm install --silent

      - name: Run Cypress Test
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./frontend
          command: npx cypress run
          browser: chrome

      - name: Build
        run: npm run build
