name: Run Frontend App

on:
  push:
    branches: [ "development","main" ]
    paths:
      -"frontend.yml"
  pull_request:
    branches: [ "development","main" ]
    paths:
      -"frontend.yml"

defaults:
 run:
  working-directory: ./frontend

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
         
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}


      - name: Install dependencies
        run: npm install --silent

      - name: Build
        run: npm run build

      - name: Run the tests
        run: npm run test
