name: Smart Championship full

on:
  push:
    branches: [ "dev-actions" ]
  pull_request:
    branches: [ "dev-actions" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
         
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}


      - name: FE Install dependencies
        working-directory: ./frontend
        run: npm install --silent

      - name: FE Build
        working-directory: ./frontend
        run: npm run build

      - name: FE Run the tests
        working-directory: ./frontend
        run: npm run test

      - name: BE Install dependencies
        working-directory: ./backend
        run: npm install --silent

      - name: BE Build
        working-directory: ./backend
        run: npm run build

      - name: BE Run the tests
        working-directory: ./backend
        run: npm run test
